const programs = [
  {
    id: 1,
    title: "Business English",
    category: "Work",
    date: "29.08.2024 - 21.04.2025",
    img: "../assets/images/img1.jpg",
    price: "17000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 2,
    title: "English for children",
    category: "Kids",
    date: "23.11.2024 - 15.04.2025",
    img: "../assets/images/img2.jpg",
    price: "8000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 3,
    title: "English for students",
    category: "Students",
    date: "29.06.2024 - 17.04.2025",
    img: "../assets/images/img3.jpg",
    price: "12000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 4,
    title: "IT English",
    category: "Work",
    date: "23.12.2024 - 21.04.2025",
    img: "../assets/images/img4.jpg",
    price: "10000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 5,
    title: "Legal English",
    category: "Work",
    date: "25.09.2024 - 03.04.2025",
    img: "../assets/images/img5.jpg",
    price: "19000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 6,
    title: "English for adults",
    category: "Adults",
    date: "28.07.2024 - 21.04.2025",
    img: "../assets/images/img6.jpg",
    price: "15000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 7,
    title: "Medical English",
    category: "Work",
    date: "17.05.2024 - 17.05.2025",
    img: "../assets/images/img7.jpg",
    price: "20000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 8,
    title: "English to travel abroad",
    category: "Adults",
    date: "23.06.2024 - 21.04.2025",
    img: "../assets/images/img8.jpg",
    price: "14000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 9,
    title: "IELTS/TOEFL English",
    category: "Students",
    date: "18.11.2024 - 03.04.2024",
    img: "../assets/images/img9.jpg",
    price: "16000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
  {
    id: 10,
    title: "Pre-school English",
    category: "Kids",
    date: "15.09.2024 - 21.05.2025",
    img: "../assets/images/img10.jpg",
    price: "6000 uah / per course",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitanihil quaerat minus libero officia magni temporibus ipsa, natusdeserunt provident necessitatibus esse harum tenetur, ill!",
  },
];

export default programs;

